### ISSUE TITLE
What about Rakugo?

### ISSUE THREAD

**Issue by Jeremi360** [zcaliptium/gddlg#1]
I making my own dialog system called Rakugo (it have more then that), maybe you want to help me?
https://github.com/rakugoteam/Rakugo

**Comment by zcaliptium** [comment]
@jebedaia360 Looked a bit... I don't really like that it has own stuff related to UIs, looks too complicated. I like to have things generic as possible to have game-specific implementation sitting in game.

But thanks for advice. ^^

**Comment by Jeremi360** [comment]
Ok, it realed to UI, to make devlopers work easier.
And also it have more that just dialog system: save/load, dialogs history, quests, options and custom nodes.
